package com.kunlunsoft.wxcp.entity;

public class WxCpCommandToSuite {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_cp_demo..wx_cp_command_to_suite.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_cp_demo..wx_cp_command_to_suite.suiteTicket
     *
     * @mbg.generated
     */
    private String suiteTicket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_cp_demo..wx_cp_command_to_suite.suiteId
     *
     * @mbg.generated
     */
    private String suiteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_cp_demo..wx_cp_command_to_suite.infoType
     *
     * @mbg.generated
     */
    private String infoType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_cp_demo..wx_cp_command_to_suite.authCode
     *
     * @mbg.generated
     */
    private String authCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_cp_demo..wx_cp_command_to_suite.timeStamp2
     *
     * @mbg.generated
     */
    private String timeStamp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_cp_demo..wx_cp_command_to_suite.createTime
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_cp_demo..wx_cp_command_to_suite.updateTime
     *
     * @mbg.generated
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_cp_demo..wx_cp_command_to_suite.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_cp_demo..wx_cp_command_to_suite.id
     *
     * @return the value of wx_cp_demo..wx_cp_command_to_suite.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_cp_demo..wx_cp_command_to_suite.id
     *
     * @param id the value for wx_cp_demo..wx_cp_command_to_suite.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_cp_demo..wx_cp_command_to_suite.suiteTicket
     *
     * @return the value of wx_cp_demo..wx_cp_command_to_suite.suiteTicket
     * @mbg.generated
     */
    public String getSuiteTicket() {
        return suiteTicket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_cp_demo..wx_cp_command_to_suite.suiteTicket
     *
     * @param suiteTicket the value for wx_cp_demo..wx_cp_command_to_suite.suiteTicket
     * @mbg.generated
     */
    public void setSuiteTicket(String suiteTicket) {
        this.suiteTicket = suiteTicket == null ? null : suiteTicket.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_cp_demo..wx_cp_command_to_suite.suiteId
     *
     * @return the value of wx_cp_demo..wx_cp_command_to_suite.suiteId
     * @mbg.generated
     */
    public String getSuiteId() {
        return suiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_cp_demo..wx_cp_command_to_suite.suiteId
     *
     * @param suiteId the value for wx_cp_demo..wx_cp_command_to_suite.suiteId
     * @mbg.generated
     */
    public void setSuiteId(String suiteId) {
        this.suiteId = suiteId == null ? null : suiteId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_cp_demo..wx_cp_command_to_suite.infoType
     *
     * @return the value of wx_cp_demo..wx_cp_command_to_suite.infoType
     * @mbg.generated
     */
    public String getInfoType() {
        return infoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_cp_demo..wx_cp_command_to_suite.infoType
     *
     * @param infoType the value for wx_cp_demo..wx_cp_command_to_suite.infoType
     * @mbg.generated
     */
    public void setInfoType(String infoType) {
        this.infoType = infoType == null ? null : infoType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_cp_demo..wx_cp_command_to_suite.authCode
     *
     * @return the value of wx_cp_demo..wx_cp_command_to_suite.authCode
     * @mbg.generated
     */
    public String getAuthCode() {
        return authCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_cp_demo..wx_cp_command_to_suite.authCode
     *
     * @param authCode the value for wx_cp_demo..wx_cp_command_to_suite.authCode
     * @mbg.generated
     */
    public void setAuthCode(String authCode) {
        this.authCode = authCode == null ? null : authCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_cp_demo..wx_cp_command_to_suite.timeStamp2
     *
     * @return the value of wx_cp_demo..wx_cp_command_to_suite.timeStamp2
     * @mbg.generated
     */
    public String getTimeStamp2() {
        return timeStamp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_cp_demo..wx_cp_command_to_suite.timeStamp2
     *
     * @param timeStamp2 the value for wx_cp_demo..wx_cp_command_to_suite.timeStamp2
     * @mbg.generated
     */
    public void setTimeStamp2(String timeStamp2) {
        this.timeStamp2 = timeStamp2 == null ? null : timeStamp2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_cp_demo..wx_cp_command_to_suite.createTime
     *
     * @return the value of wx_cp_demo..wx_cp_command_to_suite.createTime
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_cp_demo..wx_cp_command_to_suite.createTime
     *
     * @param createTime the value for wx_cp_demo..wx_cp_command_to_suite.createTime
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_cp_demo..wx_cp_command_to_suite.updateTime
     *
     * @return the value of wx_cp_demo..wx_cp_command_to_suite.updateTime
     * @mbg.generated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_cp_demo..wx_cp_command_to_suite.updateTime
     *
     * @param updateTime the value for wx_cp_demo..wx_cp_command_to_suite.updateTime
     * @mbg.generated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_cp_demo..wx_cp_command_to_suite.remark
     *
     * @return the value of wx_cp_demo..wx_cp_command_to_suite.remark
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_cp_demo..wx_cp_command_to_suite.remark
     *
     * @param remark the value for wx_cp_demo..wx_cp_command_to_suite.remark
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}